[package]
name = "count"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.49", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0.17"
predicates = "3.1.3"
